### PR TITLE
Fix prometheus.Counter.Set deprecation

### LINKED ISSUE #5: type prometheus.Counter has no field or method Set
Prometheus recently deprecated `Set` for counters:
- https://github.com/prometheus/client_golang/commit/2fee50beaa152342e8347c41edf2202c3bd5f858

```
$ go install ./...
# github.com/crobox/elasticsearch_exporter
./elasticsearch_exporter.go:520: e.counters["jvm_gc_collection_seconds_count"].WithLabelValues(allStats.ClusterName, stats.Name, collector).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:521: e.counters["jvm_gc_collection_seconds_sum"].WithLabelValues(allStats.ClusterName, stats.Name, collector).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:532: e.counters["thread_pool_completed_count"].WithLabelValues(allStats.ClusterName, stats.Name, pool).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:533: e.counters["thread_pool_rejected_count"].WithLabelValues(allStats.ClusterName, stats.Name, pool).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:555: e.counters["indices_fielddata_evictions"].WithLabelValues(allStats.ClusterName, stats.Name).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:556: e.counters["indices_fielddata_hit_count"].WithLabelValues(allStats.ClusterName, stats.Name).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:557: e.counters["indices_fielddata_total_count"].WithLabelValues(allStats.ClusterName, stats.Name).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:561: e.counters["indices_filter_cache_evictions"].WithLabelValues(allStats.ClusterName, stats.Name).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:562: e.counters["indices_filter_cache_hit_count"].WithLabelValues(allStats.ClusterName, stats.Name).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:563: e.counters["indices_filter_cache_total_count"].WithLabelValues(allStats.ClusterName, stats.Name).Set undefined (type prometheus.Counter has no field or method Set)
./elasticsearch_exporter.go:563: too many errors
```

### PR DESCRIPTION
**Pull request by GenPage**
- Replace .Set() with .Add() as per the prom docs (https://godoc.org/github.com/prometheus/client_golang/prometheus#Counter)
 - Fixes #5

### CODE REVIEW

**Comment by f1yegor** [comment]
Thanks for the PR :+1:

**Comment by bobrik** [comment]
Are you sure it's the right way? Elasticsearch reports absolute values and you just add them on every scrape.

Take number of indexed documents:

1. Elasticsearch: 5 docs, Set: 5 docs, Add: 0 + 5 = 5 docs
2. Elasricsearch: 10 docs, Set: 10 docs, Add: 5 + 10 = 15 docs

Doesn't look right to me. Did I miss something?

**Comment by f1yegor** [comment]
thanks for remark. will check and return to you. in another project I used throw away metrics with regard to documentation, so will check.

**Comment by GenPage** [comment]
Sounds like some of them need to be replaced by Gauges instead of Counters then:

```
Counter is a Metric that represents a single numerical value that only ever goes up. That implies that it cannot be used to count items whose number can also go down, e.g. the number of currently running goroutines. Those "counters" are represented by Gauges.
```

**Pull request merged**
